config/routes.rb
ProjectoPortfolio::Application.routes.draw do

  get 'registar' => 'pagina#registar'

  resources :curriculos_empregos

  resources :funcao_usuarios

  resources :funcao_concursos

  resources :funcao_empregos

  resources :industria_usuarios

  resources :industria_concursos

  resources :industria_empregos

  resources :provincia_concursos

  resources :provincia_empregos

  resources :funcaos

  resources :industria

  resources :provincia

  devise_for :usuarios

  resources :empregos

  resources :proposta

  resources :curriculos

  resources :concursos

  resources :estado_proposta

  resources :estado_curriculos

  resources :tipo_concursos

  resources :tipo_usuarios

   root 'pagina#inicio'

end

app/models/concurso.rb
class Concurso < ActiveRecord::Base
  belongs_to :tipo_concurso
end

app/models/curriculo.rb
class Curriculo < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :emprego
  belongs_to :estado_curriculo
end

app/models/emprego.rb
class Emprego < ActiveRecord::Base
  has_many :curriculos, through: :curriculos_emprego
end

app/models/estado_curriculo.rb
class EstadoCurriculo < ActiveRecord::Base
  has_many :curriculos
end

app/models/estado_proposta.rb
class EstadoProposta < ActiveRecord::Base
  has_many :propostas
end

app/models/funcao.rb
class Funcao < ActiveRecord::Base
  has_many :concursos, through: :funcao_concursos
  has_many :empregos, through: :funcao_empregos
  has_many :usuarios, through: :funcao_usuarios
end

app/models/funcao_concurso.rb
class FuncaoConcurso < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :concurso
end

app/models/funcao_emprego.rb
class FuncaoEmprego < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :emprego
end

app/models/funcao_usuario.rb
class FuncaoUsuario < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :usuario
end

app/models/industria.rb
class Industria < ActiveRecord::Base
  has_many :concursos, through: :industria_concursos
  has_many :empregos, through:  :industria_empregos
  has_many :usuarios, through: :industria_usuarios
end

app/models/proposta.rb
class Proposta < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :concurso
  belongs_to :estado_proposta
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
  has_many :concursos, through: :provincia_concursos
  has_many :empregos, through: :provincia_empregos
  has_many :usuarios
end

app/models/tipo_concurso.rb
class TipoConcurso < ActiveRecord::Base
  has_many :concursos
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :tipo_usuario
  belongs_to :provincia
end

app/controllers/funcao_empregos_controller.rb
class FuncaoEmpregosController < ApplicationController
  before_action :set_funcao_emprego, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @funcao_empregos = FuncaoEmprego.all
    respond_with(@funcao_empregos)
  end

  def show
    respond_with(@funcao_emprego)
  end

  def new
    @funcao_emprego = FuncaoEmprego.new
    respond_with(@funcao_emprego)
  end

  def edit
  end

  def create
    @funcao_emprego = FuncaoEmprego.new(funcao_emprego_params)
    @funcao_emprego.save
    respond_with(@funcao_emprego)
  end

  def update
    @funcao_emprego.update(funcao_emprego_params)
    respond_with(@funcao_emprego)
  end

  def destroy
    @funcao_emprego.destroy
    respond_with(@funcao_emprego)
  end

  private
    def set_funcao_emprego
      @funcao_emprego = FuncaoEmprego.find(params[:id])
    end

    def funcao_emprego_params
      params.require(:funcao_emprego).permit(:id_funcao, :id_emprego)
    end
end

app/helpers/concursos_helper.rb
module ConcursosHelper
end

app/helpers/empregos_helper.rb
module EmpregosHelper
end

app/helpers/funcao_empregos_helper.rb
module FuncaoEmpregosHelper
end

app/helpers/funcaos_helper.rb
module FuncaosHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/helpers/proposta_helper.rb
module PropostaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/funcao_empregos/_form.html.erb
<%= form_for(@funcao_emprego) do |f| %>
  <% if @funcao_emprego.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcao_emprego.errors.count, "error") %> prohibited this funcao_emprego from being saved:</h2>

      <ul>
      <% @funcao_emprego.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_funcao %><br>
    <%= f.number_field :id_funcao %>
  </div>
  <div class="field">
    <%= f.label :id_emprego %><br>
    <%= f.number_field :id_emprego %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcao_empregos/edit.html.erb
<h1>Editing funcao_emprego</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcao_emprego %> |
<%= link_to 'Back', funcao_empregos_path %>

app/views/funcao_empregos/index.html.erb
<h1>Listing funcao_empregos</h1>

<table>
  <thead>
    <tr>
      <th>Id funcao</th>
      <th>Id emprego</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funcao_empregos.each do |funcao_emprego| %>
      <tr>
        <td><%= funcao_emprego.id_funcao %></td>
        <td><%= funcao_emprego.id_emprego %></td>
        <td><%= link_to 'Show', funcao_emprego %></td>
        <td><%= link_to 'Edit', edit_funcao_emprego_path(funcao_emprego) %></td>
        <td><%= link_to 'Destroy', funcao_emprego, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcao emprego', new_funcao_emprego_path %>

app/views/funcao_empregos/new.html.erb
<h1>New funcao_emprego</h1>

<%= render 'form' %>

<%= link_to 'Back', funcao_empregos_path %>

app/views/funcao_empregos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id funcao:</strong>
  <%= @funcao_emprego.id_funcao %>
</p>

<p>
  <strong>Id emprego:</strong>
  <%= @funcao_emprego.id_emprego %>
</p>

<%= link_to 'Edit', edit_funcao_emprego_path(@funcao_emprego) %> |
<%= link_to 'Back', funcao_empregos_path %>