config/routes.rb
ProjectoPortfolio::Application.routes.draw do

  get 'registar' => 'pagina#registar'

  resources :curriculos_empregos

  resources :funcao_usuarios

  resources :funcao_concursos

  resources :funcao_empregos

  resources :industria_usuarios

  resources :industria_concursos

  resources :industria_empregos

  resources :provincia_concursos

  resources :provincia_empregos

  resources :funcaos

  resources :industria

  resources :provincia

  devise_for :usuarios

  resources :empregos

  resources :proposta

  resources :curriculos

  resources :concursos

  resources :estado_proposta

  resources :estado_curriculos

  resources :tipo_concursos

  resources :tipo_usuarios

   root 'pagina#inicio'

end

app/models/concurso.rb
class Concurso < ActiveRecord::Base
  belongs_to :tipo_concurso
end

app/models/curriculo.rb
class Curriculo < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :emprego
  belongs_to :estado_curriculo
end

app/models/emprego.rb
class Emprego < ActiveRecord::Base
  has_many :curriculos, through: :curriculos_emprego
end

app/models/estado_curriculo.rb
class EstadoCurriculo < ActiveRecord::Base
  has_many :curriculos
end

app/models/estado_proposta.rb
class EstadoProposta < ActiveRecord::Base
  has_many :propostas
end

app/models/funcao.rb
class Funcao < ActiveRecord::Base
  has_many :concursos, through: :funcao_concursos
  has_many :empregos, through: :funcao_empregos
  has_many :usuarios, through: :funcao_usuarios
end

app/models/funcao_concurso.rb
class FuncaoConcurso < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :concurso
end

app/models/funcao_emprego.rb
class FuncaoEmprego < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :emprego
end

app/models/funcao_usuario.rb
class FuncaoUsuario < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :usuario
end

app/models/industria.rb
class Industria < ActiveRecord::Base
  has_many :concursos, through: :industria_concursos
  has_many :empregos, through:  :industria_empregos
  has_many :usuarios, through: :industria_usuarios
end

app/models/industria_usuario.rb
class IndustriaUsuario < ActiveRecord::Base
  belongs_to :industria
  belongs_to :usuario
end

app/models/proposta.rb
class Proposta < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :concurso
  belongs_to :estado_proposta
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
  has_many :concursos, through: :provincia_concursos
  has_many :empregos, through: :provincia_empregos
  has_many :usuarios
end

app/models/tipo_concurso.rb
class TipoConcurso < ActiveRecord::Base
  has_many :concursos
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :tipo_usuario
  belongs_to :provincia
end

app/controllers/industria_usuarios_controller.rb
class IndustriaUsuariosController < ApplicationController
  before_action :set_industria_usuario, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @industria_usuarios = IndustriaUsuario.all
    respond_with(@industria_usuarios)
  end

  def show
    respond_with(@industria_usuario)
  end

  def new
    @industria_usuario = IndustriaUsuario.new
    respond_with(@industria_usuario)
  end

  def edit
  end

  def create
    @industria_usuario = IndustriaUsuario.new(industria_usuario_params)
    @industria_usuario.save
    respond_with(@industria_usuario)
  end

  def update
    @industria_usuario.update(industria_usuario_params)
    respond_with(@industria_usuario)
  end

  def destroy
    @industria_usuario.destroy
    respond_with(@industria_usuario)
  end

  private
    def set_industria_usuario
      @industria_usuario = IndustriaUsuario.find(params[:id])
    end

    def industria_usuario_params
      params.require(:industria_usuario).permit(:id_industria, :id_usuario)
    end
end

app/helpers/empregos_helper.rb
module EmpregosHelper
end

app/helpers/funcaos_helper.rb
module FuncaosHelper
end

app/helpers/industria_usuarios_helper.rb
module IndustriaUsuariosHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/helpers/proposta_helper.rb
module PropostaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/industria_usuarios/_form.html.erb
<%= form_for(@industria_usuario) do |f| %>
  <% if @industria_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industria_usuario.errors.count, "error") %> prohibited this industria_usuario from being saved:</h2>

      <ul>
      <% @industria_usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_industria %><br>
    <%= f.number_field :id_industria %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.number_field :id_usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/industria_usuarios/edit.html.erb
<h1>Editing industria_usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @industria_usuario %> |
<%= link_to 'Back', industria_usuarios_path %>

app/views/industria_usuarios/index.html.erb
<h1>Listing industria_usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Id industria</th>
      <th>Id usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @industria_usuarios.each do |industria_usuario| %>
      <tr>
        <td><%= industria_usuario.id_industria %></td>
        <td><%= industria_usuario.id_usuario %></td>
        <td><%= link_to 'Show', industria_usuario %></td>
        <td><%= link_to 'Edit', edit_industria_usuario_path(industria_usuario) %></td>
        <td><%= link_to 'Destroy', industria_usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Industria usuario', new_industria_usuario_path %>

app/views/industria_usuarios/new.html.erb
<h1>New industria_usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', industria_usuarios_path %>

app/views/industria_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id industria:</strong>
  <%= @industria_usuario.id_industria %>
</p>

<p>
  <strong>Id usuario:</strong>
  <%= @industria_usuario.id_usuario %>
</p>

<%= link_to 'Edit', edit_industria_usuario_path(@industria_usuario) %> |
<%= link_to 'Back', industria_usuarios_path %>