config/routes.rb
ProjectoPortfolio::Application.routes.draw do

  get 'registar' => 'pagina#registar'

  resources :curriculos_empregos

  resources :funcao_usuarios

  resources :funcao_concursos

  resources :funcao_empregos

  resources :industria_usuarios

  resources :industria_concursos

  resources :industria_empregos

  resources :provincia_concursos

  resources :provincia_empregos

  resources :funcaos

  resources :industria

  resources :provincia

  devise_for :usuarios

  resources :empregos

  resources :proposta

  resources :curriculos

  resources :concursos

  resources :estado_proposta

  resources :estado_curriculos

  resources :tipo_concursos

  resources :tipo_usuarios

   root 'pagina#inicio'

end

app/models/concurso.rb
class Concurso < ActiveRecord::Base
  belongs_to :tipo_concurso
end

app/models/curriculo.rb
class Curriculo < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :emprego
  belongs_to :estado_curriculo
end

app/models/curriculos_emprego.rb
class CurriculosEmprego < ActiveRecord::Base
  belongs_to :emprego
  belongs_to :curriculo
end

app/models/emprego.rb
class Emprego < ActiveRecord::Base
  has_many :curriculos, through: :curriculos_emprego
end

app/models/estado_curriculo.rb
class EstadoCurriculo < ActiveRecord::Base
  has_many :curriculos
end

app/models/estado_proposta.rb
class EstadoProposta < ActiveRecord::Base
  has_many :propostas
end

app/models/funcao.rb
class Funcao < ActiveRecord::Base
  has_many :concursos, through: :funcao_concursos
  has_many :empregos, through: :funcao_empregos
  has_many :usuarios, through: :funcao_usuarios
end

app/models/funcao_concurso.rb
class FuncaoConcurso < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :concurso
end

app/models/funcao_emprego.rb
class FuncaoEmprego < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :emprego
end

app/models/funcao_usuario.rb
class FuncaoUsuario < ActiveRecord::Base
  belongs_to :funcao
  belongs_to :usuario
end

app/models/industria.rb
class Industria < ActiveRecord::Base
  has_many :concursos, through: :industria_concursos
  has_many :empregos, through:  :industria_empregos
  has_many :usuarios, through: :industria_usuarios
end

app/models/proposta.rb
class Proposta < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :concurso
  belongs_to :estado_proposta
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
  has_many :concursos, through: :provincia_concursos
  has_many :empregos, through: :provincia_empregos
  has_many :usuarios
end

app/models/tipo_concurso.rb
class TipoConcurso < ActiveRecord::Base
  has_many :concursos
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :tipo_usuario
  belongs_to :provincia
end

app/controllers/curriculos_empregos_controller.rb
class CurriculosEmpregosController < ApplicationController
  before_action :set_curriculos_emprego, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @curriculos_empregos = CurriculosEmprego.all
    respond_with(@curriculos_empregos)
  end

  def show
    respond_with(@curriculos_emprego)
  end

  def new
    @curriculos_emprego = CurriculosEmprego.new
    respond_with(@curriculos_emprego)
  end

  def edit
  end

  def create
    @curriculos_emprego = CurriculosEmprego.new(curriculos_emprego_params)
    @curriculos_emprego.save
    respond_with(@curriculos_emprego)
  end

  def update
    @curriculos_emprego.update(curriculos_emprego_params)
    respond_with(@curriculos_emprego)
  end

  def destroy
    @curriculos_emprego.destroy
    respond_with(@curriculos_emprego)
  end

  private
    def set_curriculos_emprego
      @curriculos_emprego = CurriculosEmprego.find(params[:id])
    end

    def curriculos_emprego_params
      params.require(:curriculos_emprego).permit(:id_emprego, :id_curriculo)
    end
end

app/helpers/curriculos_empregos_helper.rb
module CurriculosEmpregosHelper
end

app/helpers/empregos_helper.rb
module EmpregosHelper
end

app/helpers/funcaos_helper.rb
module FuncaosHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/helpers/proposta_helper.rb
module PropostaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/curriculos_empregos/_form.html.erb
<%= form_for(@curriculos_emprego) do |f| %>
  <% if @curriculos_emprego.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculos_emprego.errors.count, "error") %> prohibited this curriculos_emprego from being saved:</h2>

      <ul>
      <% @curriculos_emprego.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_emprego %><br>
    <%= f.number_field :id_emprego %>
  </div>
  <div class="field">
    <%= f.label :id_curriculo %><br>
    <%= f.number_field :id_curriculo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/curriculos_empregos/edit.html.erb
<h1>Editing curriculos_emprego</h1>

<%= render 'form' %>

<%= link_to 'Show', @curriculos_emprego %> |
<%= link_to 'Back', curriculos_empregos_path %>

app/views/curriculos_empregos/index.html.erb
<h1>Listing curriculos_empregos</h1>

<table>
  <thead>
    <tr>
      <th>Id emprego</th>
      <th>Id curriculo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculos_empregos.each do |curriculos_emprego| %>
      <tr>
        <td><%= curriculos_emprego.id_emprego %></td>
        <td><%= curriculos_emprego.id_curriculo %></td>
        <td><%= link_to 'Show', curriculos_emprego %></td>
        <td><%= link_to 'Edit', edit_curriculos_emprego_path(curriculos_emprego) %></td>
        <td><%= link_to 'Destroy', curriculos_emprego, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculos emprego', new_curriculos_emprego_path %>

app/views/curriculos_empregos/new.html.erb
<h1>New curriculos_emprego</h1>

<%= render 'form' %>

<%= link_to 'Back', curriculos_empregos_path %>

app/views/curriculos_empregos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id emprego:</strong>
  <%= @curriculos_emprego.id_emprego %>
</p>

<p>
  <strong>Id curriculo:</strong>
  <%= @curriculos_emprego.id_curriculo %>
</p>

<%= link_to 'Edit', edit_curriculos_emprego_path(@curriculos_emprego) %> |
<%= link_to 'Back', curriculos_empregos_path %>